# Generated by Django 2.2.1 on 2019-09-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('calories', models.TextField()),
                ('description', models.TextField()),
                ('is_veg', models.BooleanField()),
                ('image_url', models.TextField()),
                ('price', models.TextField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fiber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calories', models.IntegerField()),
                ('sleeptime', models.FloatField()),
                ('illness', models.IntegerField()),
                ('food', models.IntegerField()),
                ('foodtime', models.IntegerField()),
                ('is_training', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, unique=True)),
                ('food', models.ManyToManyField(to='DummyData.Food')),
            ],
        ),
    ]
